# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-02 05:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name_plural': 'Social Media Links'},
        ),
        migrations.AddField(
            model_name='thing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 2, 5, 59, 31, 453431, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 2, 2, 5, 59, 51, 204518, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
